import { RepoAnalysis, Resource } from './coreApiClient.js';
import { PortfolioCopy } from './gemini.js';

export type Lang = 'en' | 'ja';

interface Strings {
  htmlLang: string;
  pageTitle: (username: string) => string;
  defaultTagline: string;
  noDescription: string;
  fork: string;
  statRepos: string;
  statStars: string;
  statLanguages: string;
  generatedBy: (date: string, hasCopy: boolean) => string;
  tabPortfolio: string;
  tabDataCore: string;
  askHeading: string;
  askPlaceholder: string;
  askButton: string;
  askThinking: string;
  askRequestFailed: string;
  featuredHeading: string;
  allReposHeading: string;
  resourcesIntro: string;
  noArtifacts: string;
  langSwitchLabel: string;
  langSwitchHref: string;
}

const STRINGS: Record<Lang, Strings> = {
  en: {
    htmlLang: 'en',
    pageTitle: (username) => `${username} — Portfolio (generated by DataCore)`,
    defaultTagline: "Public GitHub portfolio, scanned by DataCore's github-profile-scanner plugin",
    noDescription: 'No description',
    fork: 'fork',
    statRepos: 'Repositories',
    statStars: 'Total Stars',
    statLanguages: 'Languages',
    generatedBy: (date, hasCopy) =>
      `Generated ${date} from a single <code>REPO_ANALYSIS</code> artifact via ` +
      `<a href="https://github.com/d-chebastian/datacore" target="_blank" rel="noreferrer">DataCore</a>` +
      `${hasCopy ? ', copy written by Gemini' : ''} — see <code>examples/github-portfolio</code> for the script that made this page.`,
    tabPortfolio: 'Portfolio',
    tabDataCore: 'DataCore Resources',
    askHeading: 'Ask About My Work',
    askPlaceholder: "e.g. What's your experience with event-driven systems?",
    askButton: 'Ask',
    askThinking: 'Thinking...',
    askRequestFailed: 'Request failed — is the server running?',
    featuredHeading: 'Featured Projects',
    allReposHeading: 'All Public Repositories',
    resourcesIntro:
      'This is what actually ran behind the scenes in DataCore to produce the Portfolio tab — every ' +
      'resource this example script registered or reused, exactly as the Core API reports it right now ' +
      '(not a mock). See <code>examples/github-portfolio</code> for the script.',
    noArtifacts: 'No artifacts yet',
    langSwitchLabel: '日本語',
    langSwitchHref: 'ja/portfolio.html',
  },
  ja: {
    htmlLang: 'ja',
    pageTitle: (username) => `${username} — ポートフォリオ (DataCore生成)`,
    defaultTagline: 'DataCoreの github-profile-scanner プラグインによってスキャンされた公開GitHubポートフォリオ',
    noDescription: '説明なし',
    fork: 'フォーク',
    statRepos: 'リポジトリ',
    statStars: '合計スター数',
    statLanguages: '言語',
    generatedBy: (date, hasCopy) =>
      `${date} に、単一の <code>REPO_ANALYSIS</code> 成果物から ` +
      `<a href="https://github.com/d-chebastian/datacore" target="_blank" rel="noreferrer">DataCore</a> 経由で生成` +
      `${hasCopy ? '(文章はGeminiが作成)' : ''} — このページを作成したスクリプトは <code>examples/github-portfolio</code> を参照してください。`,
    tabPortfolio: 'ポートフォリオ',
    tabDataCore: 'DataCoreリソース',
    askHeading: '私の仕事について質問する',
    askPlaceholder: '例: イベント駆動システムの経験はありますか?',
    askButton: '質問する',
    askThinking: '考え中...',
    askRequestFailed: 'リクエストに失敗しました — サーバーは起動していますか?',
    featuredHeading: '注目のプロジェクト',
    allReposHeading: 'すべての公開リポジトリ',
    resourcesIntro:
      'これは、ポートフォリオタブを生成するためにDataCoreの背後で実際に実行された内容です — このサンプル' +
      'スクリプトが登録または再利用したすべてのリソースを、Core APIが今まさに報告している通りに表示しています' +
      '(モックではありません)。スクリプトは <code>examples/github-portfolio</code> を参照してください。',
    noArtifacts: 'まだ成果物はありません',
    langSwitchLabel: 'English',
    langSwitchHref: '../portfolio.html',
  },
};

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
}

function repoCard(repo: RepoAnalysis['repos'][number], t: Strings): string {
  return `
    <a class="card" href="${escapeHtml(repo.url)}" target="_blank" rel="noreferrer">
      <div class="card-head">
        <h3>${escapeHtml(repo.name)}</h3>
        ${repo.is_fork ? `<span class="badge badge-fork">${escapeHtml(t.fork)}</span>` : ''}
      </div>
      <p class="desc">${repo.description ? escapeHtml(repo.description) : `<em>${escapeHtml(t.noDescription)}</em>`}</p>
      <div class="card-foot">
        ${repo.language ? `<span class="badge badge-lang">${escapeHtml(repo.language)}</span>` : ''}
        <span class="stat">★ ${repo.stars.toLocaleString()}</span>
        <span class="stat">⑂ ${repo.forks.toLocaleString()}</span>
      </div>
    </a>`;
}

function highlightCard(repo: RepoAnalysis['repos'][number], highlight: string): string {
  return `
    <a class="highlight-card" href="${escapeHtml(repo.url)}" target="_blank" rel="noreferrer">
      <div class="card-head">
        <h3>${escapeHtml(repo.name)}</h3>
        ${repo.language ? `<span class="badge badge-lang">${escapeHtml(repo.language)}</span>` : ''}
      </div>
      <p class="desc">${escapeHtml(highlight)}</p>
      <div class="card-foot">
        <span class="stat">★ ${repo.stars.toLocaleString()}</span>
      </div>
    </a>`;
}

const STATUS_BADGE_CLASS: Record<string, string> = {
  COMPLETED: 'badge-status-completed',
  PROCESSING: 'badge-status-processing',
  PENDING: 'badge-status-processing',
  FAILED: 'badge-status-failed',
};

function resourceCard(resource: Resource, t: Strings): string {
  const statusClass = STATUS_BADGE_CLASS[resource.status] ?? '';
  return `
    <div class="resource-card">
      <div class="card-head">
        <h3>${escapeHtml(resource.name)}</h3>
        <span class="badge ${statusClass}">${escapeHtml(resource.status)}</span>
      </div>
      <div class="card-foot" style="margin-bottom: 8px;">
        <span class="badge badge-lang">${escapeHtml(resource.type)}</span>
        ${resource.source_uri ? `<a href="${escapeHtml(resource.source_uri)}" target="_blank" rel="noreferrer" class="resource-source">${escapeHtml(resource.source_uri)}</a>` : ''}
      </div>
      ${
        resource.failure_reason
          ? `<p class="desc ask-error">${escapeHtml(resource.failure_reason)}</p>`
          : resource.artifacts.length
            ? `<div class="artifact-list">
          ${resource.artifacts
            .map(
              (a) =>
                `<div class="artifact-row"><span class="badge badge-artifact">${escapeHtml(a.type)}</span><code>${escapeHtml(a.external_ref)}</code></div>`,
            )
            .join('')}
        </div>`
            : `<p class="desc"><em>${escapeHtml(t.noArtifacts)}</em></p>`
      }
    </div>`;
}

export function renderPortfolio(
  analysis: RepoAnalysis,
  copy: PortfolioCopy | null,
  hasSearch: boolean,
  dataCoreResources: Resource[] = [],
  lang: Lang = 'en',
): string {
  const t = STRINGS[lang];
  const repos = [...analysis.repos].sort((a, b) => b.stars - a.stars || a.name.localeCompare(b.name));
  const totalStars = repos.reduce((sum, r) => sum + r.stars, 0);
  const rawLanguages = [...new Set(repos.map((r) => r.language).filter((l): l is string => Boolean(l)))];
  const scannedDate = new Date(analysis.scanned_at).toLocaleString(lang === 'ja' ? 'ja-JP' : 'en-US');

  const tagline = copy?.tagline ?? t.defaultTagline;
  const skills = copy?.skills?.length ? copy.skills : rawLanguages;
  const highlightsByRepoName = new Map((copy?.highlights ?? []).map((h) => [h.repo_name, h.highlight]));
  const highlightRepos = repos.filter((r) => !r.is_fork && highlightsByRepoName.has(r.name)).slice(0, 6);

  return `<!doctype html>
<html lang="${t.htmlLang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(t.pageTitle(analysis.username))}</title>
<style>
  :root { color-scheme: dark; }
  * { box-sizing: border-box; }
  body {
    margin: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: #0d1117; color: #e6edf3;
  }
  header {
    max-width: 720px; margin: 0 auto; padding: 48px 24px 24px; text-align: center; position: relative;
  }
  .lang-switch {
    position: absolute; top: 16px; right: 24px; font-size: 0.8rem; color: #58a6ff; text-decoration: none;
    border: 1px solid #30363d; border-radius: 999px; padding: 4px 12px;
  }
  .lang-switch:hover { border-color: #58a6ff; }
  header img { width: 96px; height: 96px; border-radius: 50%; border: 2px solid #30363d; }
  header h1 { margin: 16px 0 4px; font-size: 1.8rem; }
  header p.tagline { color: #c9d1d9; font-size: 1.05rem; margin: 0 0 16px; }
  header p.bio { color: #8b949e; font-size: 0.95rem; line-height: 1.6; margin: 0 0 20px; }
  .stats { display: flex; justify-content: center; gap: 24px; flex-wrap: wrap; margin-bottom: 20px; }
  .stats div { text-align: center; }
  .stats .num { font-size: 1.4rem; font-weight: 600; }
  .stats .label { font-size: 0.8rem; color: #8b949e; }
  .skills { display: flex; justify-content: center; flex-wrap: wrap; gap: 8px; margin-bottom: 8px; }
  .skill-chip {
    padding: 4px 12px; border-radius: 999px; font-size: 0.8rem; border: 1px solid #30363d;
    background: #161b22; color: #c9d1d9;
  }
  .generated-by { font-size: 0.75rem; color: #6e7681; margin-top: 24px; }
  .generated-by a { color: #58a6ff; }
  main { max-width: 960px; margin: 0 auto; padding: 0 24px 48px; }
  section { margin-bottom: 40px; }
  section h2 {
    font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.08em; color: #8b949e;
    margin: 0 0 16px; padding-bottom: 8px; border-bottom: 1px solid #21262d;
  }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); gap: 16px; }
  .card, .highlight-card {
    display: block; background: #161b22; border: 1px solid #30363d; border-radius: 10px; padding: 16px;
    text-decoration: none; color: inherit; transition: border-color 0.15s;
  }
  .highlight-card { background: #161b22; border-color: #1f6feb44; }
  .card:hover, .highlight-card:hover { border-color: #58a6ff; }
  .card-head { display: flex; align-items: center; justify-content: space-between; gap: 8px; }
  .card-head h3 { margin: 0; font-size: 1rem; color: #58a6ff; overflow-wrap: anywhere; }
  .desc { color: #8b949e; font-size: 0.85rem; min-height: 2.4em; margin: 8px 0; }
  .card-foot { display: flex; align-items: center; gap: 12px; flex-wrap: wrap; font-size: 0.8rem; color: #8b949e; }
  .badge { padding: 2px 8px; border-radius: 999px; font-size: 0.7rem; border: 1px solid #30363d; }
  .badge-lang { background: #1f2937; }
  .badge-fork { color: #8b949e; }
  .stat { display: inline-flex; align-items: center; gap: 3px; }
  .ask-box { background: #161b22; border: 1px solid #30363d; border-radius: 12px; padding: 20px; }
  .ask-form { display: flex; gap: 8px; }
  .ask-form input {
    flex: 1; background: #0d1117; border: 1px solid #30363d; border-radius: 8px; padding: 10px 14px;
    color: #e6edf3; font-size: 0.9rem;
  }
  .ask-form button {
    background: #1f6feb; color: white; border: none; border-radius: 8px; padding: 10px 18px;
    font-size: 0.9rem; font-weight: 500; cursor: pointer;
  }
  .ask-form button:disabled { opacity: 0.6; cursor: default; }
  .ask-answer { margin-top: 16px; font-size: 0.9rem; line-height: 1.6; color: #c9d1d9; display: none; }
  .ask-answer.visible { display: block; }
  .ask-sources { margin-top: 10px; display: flex; flex-wrap: wrap; gap: 8px; }
  .ask-sources a {
    font-size: 0.75rem; color: #58a6ff; text-decoration: none; border: 1px solid #30363d;
    border-radius: 999px; padding: 3px 10px;
  }
  .ask-sources a:hover { border-color: #58a6ff; }
  .ask-error { color: #f85149; }
  .tab-bar {
    display: flex; justify-content: center; gap: 4px; max-width: 960px; margin: 0 auto 32px;
    padding: 0 24px; border-bottom: 1px solid #21262d;
  }
  .tab-button {
    background: none; border: none; color: #8b949e; font-size: 0.9rem; font-weight: 500; cursor: pointer;
    padding: 12px 18px; border-bottom: 2px solid transparent; margin-bottom: -1px;
  }
  .tab-button.active { color: #e6edf3; border-bottom-color: #1f6feb; }
  .tab-button:hover { color: #e6edf3; }
  .tab-panel { display: none; }
  .tab-panel.active { display: block; }
  .tab-intro { color: #8b949e; font-size: 0.85rem; margin: 0 0 24px; }
  .resource-card {
    background: #161b22; border: 1px solid #30363d; border-radius: 10px; padding: 16px; margin-bottom: 16px;
  }
  .resource-source { font-size: 0.8rem; color: #58a6ff; text-decoration: none; overflow-wrap: anywhere; }
  .badge-status-completed { background: #023b1a; color: #3fb950; border-color: #2ea04333; }
  .badge-status-processing { background: #3b2f00; color: #d29922; border-color: #d2992233; }
  .badge-status-failed { background: #3b0a0a; color: #f85149; border-color: #f8514933; }
  .badge-artifact { background: #1f2937; color: #a5d6ff; }
  .artifact-list { display: flex; flex-direction: column; gap: 6px; }
  .artifact-row { display: flex; align-items: center; gap: 8px; font-size: 0.8rem; }
  .artifact-row code {
    color: #8b949e; overflow-wrap: anywhere; background: #0d1117; padding: 2px 6px; border-radius: 4px;
  }
</style>
</head>
<body>
  <header>
    <a class="lang-switch" href="${t.langSwitchHref}">${escapeHtml(t.langSwitchLabel)}</a>
    <img src="https://github.com/${escapeHtml(analysis.username)}.png" alt="${escapeHtml(analysis.username)}" />
    <h1>${escapeHtml(analysis.username)}</h1>
    <p class="tagline">${escapeHtml(tagline)}</p>
    ${copy?.bio ? `<p class="bio">${escapeHtml(copy.bio)}</p>` : ''}
    <div class="stats">
      <div><div class="num">${analysis.repo_count}</div><div class="label">${escapeHtml(t.statRepos)}</div></div>
      <div><div class="num">${totalStars.toLocaleString()}</div><div class="label">${escapeHtml(t.statStars)}</div></div>
      <div><div class="num">${rawLanguages.length}</div><div class="label">${escapeHtml(t.statLanguages)}</div></div>
    </div>
    ${skills.length ? `<div class="skills">${skills.map((s) => `<span class="skill-chip">${escapeHtml(s)}</span>`).join('')}</div>` : ''}
    <p class="generated-by">${t.generatedBy(escapeHtml(scannedDate), Boolean(copy))}</p>
  </header>
  <div class="tab-bar">
    <button class="tab-button active" data-tab="portfolio" type="button">${escapeHtml(t.tabPortfolio)}</button>
    <button class="tab-button" data-tab="datacore" type="button">${escapeHtml(t.tabDataCore)}</button>
  </div>
  <main>
    <div class="tab-panel active" id="tab-portfolio">
    ${
      hasSearch
        ? `<section>
      <h2>${escapeHtml(t.askHeading)}</h2>
      <div class="ask-box">
        <form class="ask-form" id="ask-form">
          <input type="text" id="ask-input" placeholder="${escapeHtml(t.askPlaceholder)}" required />
          <button type="submit" id="ask-submit">${escapeHtml(t.askButton)}</button>
        </form>
        <div class="ask-answer" id="ask-answer"></div>
      </div>
    </section>`
        : ''
    }
    ${
      highlightRepos.length
        ? `<section>
      <h2>${escapeHtml(t.featuredHeading)}</h2>
      <div class="grid">
        ${highlightRepos.map((r) => highlightCard(r, highlightsByRepoName.get(r.name)!)).join('\n')}
      </div>
    </section>`
        : ''
    }
    <section>
      <h2>${escapeHtml(t.allReposHeading)}</h2>
      <div class="grid">
        ${repos.map((r) => repoCard(r, t)).join('\n')}
      </div>
    </section>
    </div>
    <div class="tab-panel" id="tab-datacore">
      <p class="tab-intro">${t.resourcesIntro}</p>
      ${dataCoreResources.map((r) => resourceCard(r, t)).join('\n')}
    </div>
  </main>
  <script>
    (function () {
      var buttons = document.querySelectorAll('.tab-button');
      var panels = { portfolio: document.getElementById('tab-portfolio'), datacore: document.getElementById('tab-datacore') };
      buttons.forEach(function (btn) {
        btn.addEventListener('click', function () {
          buttons.forEach(function (b) { b.classList.remove('active'); });
          Object.keys(panels).forEach(function (k) { panels[k].classList.remove('active'); });
          btn.classList.add('active');
          panels[btn.getAttribute('data-tab')].classList.add('active');
        });
      });
    })();
  </script>
  ${
    hasSearch
      ? `<script>
    (function () {
      var form = document.getElementById('ask-form');
      var input = document.getElementById('ask-input');
      var button = document.getElementById('ask-submit');
      var answerBox = document.getElementById('ask-answer');
      var lang = ${JSON.stringify(lang)};
      var askButtonLabel = ${JSON.stringify(t.askButton)};

      form.addEventListener('submit', function (e) {
        e.preventDefault();
        var question = input.value.trim();
        if (!question) return;

        button.disabled = true;
        button.textContent = ${JSON.stringify(t.askThinking)};
        answerBox.className = 'ask-answer visible';
        answerBox.textContent = '';

        fetch('/api/ask', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ question: question, lang: lang }),
        })
          .then(function (res) { return res.json(); })
          .then(function (data) {
            if (data.error) {
              answerBox.innerHTML = '<span class="ask-error">' + data.error + '</span>';
              return;
            }
            var html = '<p>' + data.answer + '</p>';
            if (data.sources && data.sources.length) {
              html += '<div class="ask-sources">' + data.sources.map(function (s) {
                return '<a href="' + s.url + '" target="_blank" rel="noreferrer">' + s.repo_name + '</a>';
              }).join('') + '</div>';
            }
            answerBox.innerHTML = html;
          })
          .catch(function () {
            answerBox.innerHTML = '<span class="ask-error">' + ${JSON.stringify(t.askRequestFailed)} + '</span>';
          })
          .finally(function () {
            button.disabled = false;
            button.textContent = askButtonLabel;
          });
      });
    })();
  </script>`
      : ''
  }
</body>
</html>
`;
}
